server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000 # 30天，单位为秒
spring:
  servlet:
    multipart:
      # 最大文件上传体积 2MB
      max-file-size: 2MB
  mvc:
    async:
      # 异步请求超时时间，-1 表示不超时（SSE 长连接需要）
      request-timeout: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_nocode_backend
    username: root
    password: root
  # Redis 配置
  data:
    redis:
      host: 192.168.88.130
      port: 6379
      password: 123456
      ttl: 3600
      database: 1
  session:
    timeout: 2592000 # 30天，单位为秒
    store-type: redis
  profiles:
    active: local
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.hefng.mynocodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://open.bigmodel.cn/api/paas/v4
#      api-key: "<Your API Key>"
#      model-name: glm-4.6
#      log-requests: true
#      log-responses: true
#      max-tokens: 16384
#    streaming-chat-model:
#      base-url: https://open.bigmodel.cn/api/paas/v4
#      api-key: "<Your API Key>"
#      model-name: glm-4.7-flash
#      log-requests: true
#      log-responses: true
#      max-tokens: 16384
#  memory:
#    max-messages: 20
#    redis-key-prefix: "lc4j:chat_memory:"
#    ttl-seconds: 604800 # 7天