server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000 # 30天，单位为秒
spring:
  session:
    timeout: 2592000 # 30天，单位为秒
    store-type: redis
  servlet:
    multipart:
      # 最大文件上传体积 2MB
      max-file-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_nocode_backend
    username: root
    password: root
  # Redis 配置
  data:
    redis:
      host: 192.168.88.130
      port: 6379
      password: 123456
      ttl: 3600
  profiles:
    active: local
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.hefng.mynocodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: "sk-ee7bd46aa4e54b84a6e47e937a30a7f9"
#      model-name: deepseek-chat
#      log-requests: true
#      log-responses: true
#      max-tokens: 8192
#      temperature: 0.4
#      strict-json-schema: true
#      response-format: json_object
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: "sk-ee7bd46aa4e54b84a6e47e937a30a7f9"
#      model-name: deepseek-chat
#      log-requests: true
#      log-responses: true
#      max-tokens: 8192
#      temperature: 0.4

